"""Marzi WhatsApp Conversation — read-only virtual DocType backed by `/dashboard/conversations` (whatsapp).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziWhatsAppConversation(ApiDocument):
	DOCTYPE = "Marzi WhatsApp Conversation"
	api_endpoint = "/dashboard/conversations"
	api_detail_endpoint = None
	api_id_field = "mobile"
	api_service = "whatsapp"
	api_list_key = 'data.items'
	api_item_key = None
	api_auth = False
	api_single_from_list = True
	api_merge_keys = ()
	api_field_aliases = {'name': 'contact_name', 'fullName': 'full_name', 'lastMessage': 'last_message', 'lastMessageDirection': 'last_message_direction', 'lastInteraction': 'last_interaction', 'flowState': 'flow_state', 'conversationId': 'conversation_id'}
	api_child_tables = {}
	api_list_params = {}
	api_cursor_key = None
	api_detail_merge_list = False
	api_write_fields = ()
	api_write_endpoint = None
	api_write_id_field = None
	api_update_method = 'PATCH'
	api_can_create = True
	api_can_delete = True
	api_write_aliases = {}
	api_nested_fields = {}
	api_read_nested = {}
	api_write_child_tables = {}
	api_write_array_fields = ()

	@staticmethod
	def get_list(**kwargs):
		return MarziWhatsAppConversation._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziWhatsAppConversation._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
