"""Marzi FAQ Group — read-only virtual DocType backed by `/admin/event-library/faq-groups` (v1).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziFAQGroup(ApiDocument):
	DOCTYPE = "Marzi FAQ Group"
	api_endpoint = "/admin/event-library/faq-groups"
	api_detail_endpoint = None
	api_id_field = "id"
	api_service = "v1"
	api_list_key = 'faq_groups'
	api_item_key = None
	api_auth = True
	api_single_from_list = True
	api_merge_keys = ()
	api_field_aliases = {'name': 'group_name'}
	api_child_tables = {'faqs': {'doctype': 'Marzi FAQ Item', 'source': 'item', 'item_key': 'faqs', 'aliases': {}}}
	api_list_params = {}
	api_cursor_key = None
	api_detail_merge_list = False

	@staticmethod
	def get_list(**kwargs):
		return MarziFAQGroup._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziFAQGroup._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
