"""Marzi Testimony — read-only virtual DocType backed by `/admin/testimonials` (v1).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziTestimony(ApiDocument):
	DOCTYPE = "Marzi Testimony"
	api_endpoint = "/admin/testimonials"
	api_detail_endpoint = None
	api_id_field = "testimony_id"
	api_service = "v1"
	api_list_key = 'testimonies'
	api_item_key = None
	api_auth = True
	api_single_from_list = True
	api_merge_keys = ()
	api_field_aliases = {'name': 'person_name', 'author_name': 'person_name', 'content': 'quote', 'author_pic_url': 'image_url'}
	api_child_tables = {}
	api_list_params = {}
	api_cursor_key = None
	api_detail_merge_list = False
	api_write_fields = ('person_name', 'quote', 'image_url', 'video_url', 'age', 'location', 'rating', 'is_published', 'display_order')
	api_write_endpoint = None
	api_write_id_field = None
	api_update_method = 'PATCH'
	api_can_create = True
	api_can_delete = True
	api_write_aliases = {'person_name': 'name', 'quote': 'quote', 'image_url': 'image', 'video_url': 'videoUrl'}
	api_nested_fields = {}
	api_read_nested = {}
	api_write_child_tables = {}
	api_write_array_fields = ()

	@staticmethod
	def get_list(**kwargs):
		return MarziTestimony._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziTestimony._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
