"""Marzi Event — read-only virtual DocType backed by `/admin/events` (v1).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziEvent(ApiDocument):
	DOCTYPE = "Marzi Event"
	api_endpoint = "/admin/events"
	api_detail_endpoint = '/events'
	api_id_field = "id"
	api_service = "v1"
	api_list_key = 'events'
	api_item_key = None
	api_auth = True
	api_single_from_list = False
	api_merge_keys = ()
	api_field_aliases = {}
	api_child_tables = {'attendees': {'doctype': 'Marzi Event Attendee', 'source': '/events/{id}/attendees', 'list_key': 'attendees', 'aliases': {'name': 'attendee_name'}}, 'tiers': {'doctype': 'Marzi Event Tier', 'source': 'item', 'item_key': 'tiers', 'aliases': {}}}
	api_list_params = {}
	api_cursor_key = None
	api_detail_merge_list = False

	@staticmethod
	def get_list(**kwargs):
		return MarziEvent._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziEvent._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
