"""Marzi Page — read-only virtual DocType backed by `/v1/publishing/admin/pages` (publishing).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziPage(ApiDocument):
	DOCTYPE = "Marzi Page"
	api_endpoint = "/v1/publishing/admin/pages"
	api_detail_endpoint = '/v1/publishing/admin/pages'
	api_id_field = "id"
	api_service = "publishing"
	api_list_key = None
	api_item_key = None
	api_auth = True
	api_single_from_list = False
	api_merge_keys = ()
	api_field_aliases = {'templateId': 'template_id', 'pathPrefix': 'path_prefix', 'pageType': 'type', 'metaTitle': 'meta_title', 'metaDescription': 'meta_description', 'metaKeywords': 'meta_keywords', 'primaryKeyword': 'primary_keyword', 'secondaryKeywords': 'secondary_keywords', 'robotsIndex': 'robots_index', 'robotsFollow': 'robots_follow', 'sitemapInclude': 'sitemap_include', 'canonicalUrl': 'canonical_url', 'heroImageUrl': 'hero_image_url', 'heroImageAlt': 'hero_image_alt', 'mobileHeroImageUrl': 'mobile_hero_image_url', 'featuredImageUrl': 'featured_image_url', 'ogImageUrl': 'og_image_url', 'ogTitle': 'og_title', 'ogDescription': 'og_description', 'twitterCard': 'twitter_card', 'aboutSection': 'about_section', 'publishedAt': 'published_at', 'createdAt': 'created_at', 'updatedAt': 'updated_at'}
	api_child_tables = {}
	api_list_params = {}
	api_cursor_key = None
	api_detail_merge_list = False

	@staticmethod
	def get_list(**kwargs):
		return MarziPage._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziPage._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
