"""Marzi User — read-only virtual DocType backed by `/users` (v1).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziUser(ApiDocument):
	DOCTYPE = "Marzi User"
	api_endpoint = "/users"
	api_detail_endpoint = '/users'
	api_id_field = "userId"
	api_service = "v1"
	api_list_key = 'items'
	api_item_key = None
	api_auth = True
	api_single_from_list = False
	api_merge_keys = ()
	api_field_aliases = {'firstName': 'first_name', 'lastName': 'last_name', 'accountStatus': 'account_status', 'createdAt': 'created_at', 'profilePicUrl': 'profile_pic_url', 'totalBadges': 'total_badges', 'totalEvents': 'total_events', 'totalTransactions': 'total_transactions', 'totalPosts': 'total_posts', 'eventsBooked': 'events_booked', 'isOnboardingCompleted': 'is_onboarding_completed', 'isFirstDiscountApplied': 'is_first_discount_applied'}
	api_child_tables = {'bookings': {'doctype': 'Marzi User Booking', 'source': 'item', 'item_key': 'events', 'aliases': {'bookingId': 'booking_id', 'eventId': 'event_id', 'eventTitle': 'event_title', 'eventStartTime': 'event_start_time', 'seatsBooked': 'seats_booked', 'confirmationNumber': 'confirmation_number', 'totalAmount': 'total_amount', 'paidAt': 'paid_at', 'createdAt': 'created_at'}}, 'transactions': {'doctype': 'Marzi User Transaction', 'source': 'item', 'item_key': 'transactions', 'aliases': {'transactionId': 'transaction_id', 'eventId': 'event_id', 'eventTitle': 'event_title', 'totalAmount': 'total_amount', 'discountAmount': 'discount_amount', 'promoCode': 'promo_code', 'confirmationNumber': 'confirmation_number', 'razorpayOrderId': 'razorpay_order_id', 'razorpayPaymentId': 'razorpay_payment_id', 'paidAt': 'paid_at', 'createdAt': 'created_at'}}}
	api_list_params = {'limit': 50}
	api_cursor_key = 'nextCursor'
	api_detail_merge_list = True
	api_write_fields = ()
	api_write_endpoint = None
	api_write_id_field = None
	api_update_method = 'PATCH'
	api_can_create = True
	api_can_delete = True
	api_write_aliases = {}
	api_nested_fields = {}
	api_read_nested = {}
	api_write_child_tables = {}
	api_write_array_fields = ()

	@staticmethod
	def get_list(**kwargs):
		return MarziUser._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziUser._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
