"""Marzi Template — read-only virtual DocType backed by `/v1/publishing/admin/templates` (publishing).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziTemplate(ApiDocument):
	DOCTYPE = "Marzi Template"
	api_endpoint = "/v1/publishing/admin/templates"
	api_detail_endpoint = None
	api_id_field = "id"
	api_service = "publishing"
	api_list_key = 'templates'
	api_item_key = None
	api_auth = True
	api_single_from_list = True
	api_merge_keys = ()
	api_field_aliases = {'name': 'template_name'}
	api_child_tables = {}

	@staticmethod
	def get_list(**kwargs):
		return MarziTemplate._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziTemplate._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
