"""Marzi Group Member — istable virtual child DocType, populated by its parent's load_from_db.

Auto-generated by scripts/gen_doctypes.py. Never listed on its own.
"""

from marzi_bridge.api_document import ApiDocument


class MarziGroupMember(ApiDocument):
	DOCTYPE = "Marzi Group Member"

	@staticmethod
	def get_list(**kwargs):
		return []

	@staticmethod
	def get_count(**kwargs):
		return 0

	@staticmethod
	def get_stats(**kwargs):
		return {}
