"""Marzi Escalation — read-only virtual DocType backed by `/dashboard/escalations/pending` (v1).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziEscalation(ApiDocument):
	DOCTYPE = "Marzi Escalation"
	api_endpoint = "/dashboard/escalations/pending"
	api_detail_endpoint = None
	api_id_field = "escalationId"
	api_service = "v1"
	api_list_key = 'data'
	api_item_key = None
	api_auth = True
	api_single_from_list = True
	api_merge_keys = ()
	api_field_aliases = {'agentHandling': 'agent_handling', 'updatedAt': 'updated_at', 'resolvedAt': 'resolved_at', 'resolvedBy': 'resolved_by', 'userMessage': 'user_message'}
	api_child_tables = {}
	api_list_params = {}
	api_cursor_key = None
	api_detail_merge_list = False
	api_write_fields = ('status', 'notes', 'resolved_by')
	api_write_endpoint = '/dashboard/escalations'
	api_write_id_field = None
	api_update_method = 'PATCH'
	api_can_create = False
	api_can_delete = False
	api_write_aliases = {'resolved_by': 'resolvedBy'}
	api_nested_fields = {}
	api_read_nested = {}
	api_write_child_tables = {}
	api_write_array_fields = ()

	@staticmethod
	def get_list(**kwargs):
		return MarziEscalation._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziEscalation._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
