"""Marzi Info Item — read-only virtual DocType backed by `/admin/event-library/info-items` (v1).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziInfoItem(ApiDocument):
	DOCTYPE = "Marzi Info Item"
	api_endpoint = "/admin/event-library/info-items"
	api_detail_endpoint = None
	api_id_field = "id"
	api_service = "v1"
	api_list_key = 'info_items'
	api_item_key = None
	api_auth = True
	api_single_from_list = True
	api_merge_keys = ()
	api_field_aliases = {}
	api_child_tables = {}
	api_list_params = {}
	api_cursor_key = None
	api_detail_merge_list = False

	@staticmethod
	def get_list(**kwargs):
		return MarziInfoItem._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziInfoItem._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
