"""Marzi Blog Post — read-only virtual DocType backed by `/admin/posts` (blog).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziBlogPost(ApiDocument):
	DOCTYPE = "Marzi Blog Post"
	api_endpoint = "/admin/posts"
	api_detail_endpoint = '/admin/posts'
	api_id_field = "id"
	api_service = "blog"
	api_list_key = 'posts'
	api_item_key = 'post'
	api_auth = True
	api_single_from_list = False
	api_merge_keys = ('tags',)
	api_field_aliases = {}
	api_child_tables = {'tags': {'doctype': 'Marzi Blog Tag', 'source': 'item', 'item_key': 'tags', 'aliases': {'name': 'tag_name'}}}
	api_list_params = {}
	api_cursor_key = None
	api_detail_merge_list = False

	@staticmethod
	def get_list(**kwargs):
		return MarziBlogPost._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziBlogPost._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
