"""Marzi Campaign — read-only virtual DocType backed by `/v1/publishing/admin/campaigns` (publishing).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziCampaign(ApiDocument):
	DOCTYPE = "Marzi Campaign"
	api_endpoint = "/v1/publishing/admin/campaigns"
	api_detail_endpoint = None
	api_id_field = "campaign_name"
	api_service = "publishing"
	api_list_key = 'campaigns'
	api_item_key = None
	api_auth = True
	api_single_from_list = True
	api_merge_keys = ()
	api_field_aliases = {}
	api_child_tables = {}
	api_list_params = {}
	api_cursor_key = None
	api_detail_merge_list = False

	@staticmethod
	def get_list(**kwargs):
		return MarziCampaign._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziCampaign._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
