"""Marzi Group — read-only virtual DocType backed by `/groups` (v1).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziGroup(ApiDocument):
	DOCTYPE = "Marzi Group"
	api_endpoint = "/groups"
	api_detail_endpoint = None
	api_id_field = "group_id"
	api_service = "v1"
	api_list_key = 'groups'
	api_item_key = None
	api_auth = True
	api_single_from_list = False
	api_merge_keys = ()
	api_field_aliases = {'name': 'group_name'}
	api_child_tables = {'members': {'doctype': 'Marzi Group Member', 'source': '/groups/{id}/members', 'list_key': 'members', 'aliases': {}}, 'posts': {'doctype': 'Marzi Group Post', 'source': '/groups/{id}/posts', 'list_key': 'posts', 'aliases': {}}}
	api_list_params = {}
	api_cursor_key = None
	api_detail_merge_list = False
	api_write_fields = ('group_name', 'description', 'category', 'type', 'city', 'interests', 'rules', 'tags')
	api_write_endpoint = None
	api_write_id_field = None
	api_update_method = 'PATCH'
	api_can_create = True
	api_can_delete = True
	api_write_aliases = {'group_name': 'name'}
	api_nested_fields = {}
	api_read_nested = {}
	api_write_child_tables = {}
	api_write_array_fields = ()

	@staticmethod
	def get_list(**kwargs):
		return MarziGroup._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziGroup._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
