"""Marzi Group — read-only virtual DocType backed by `/groups` (v1).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziGroup(ApiDocument):
	DOCTYPE = "Marzi Group"
	api_endpoint = "/groups"
	api_detail_endpoint = None
	api_id_field = "group_id"
	api_service = "v1"
	api_list_key = 'groups'
	api_item_key = None
	api_auth = True
	api_single_from_list = False
	api_merge_keys = ()
	api_field_aliases = {'name': 'group_name'}
	api_child_tables = {'members': {'doctype': 'Marzi Group Member', 'source': '/groups/{id}/members', 'list_key': 'members', 'aliases': {}}, 'posts': {'doctype': 'Marzi Group Post', 'source': '/groups/{id}/posts', 'list_key': 'posts', 'aliases': {}}}
	api_list_params = {}
	api_cursor_key = None
	api_detail_merge_list = False

	@staticmethod
	def get_list(**kwargs):
		return MarziGroup._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziGroup._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
