"""Marzi Media — read-only virtual DocType backed by `/media` (v1).

Auto-generated by scripts/gen_doctypes.py. Data lives in Backend-for-org and is
read live via MarziClient (see marzi_bridge.api_document.ApiDocument).
"""

from marzi_bridge.api_document import ApiDocument


class MarziMedia(ApiDocument):
	DOCTYPE = "Marzi Media"
	api_endpoint = "/media"
	api_detail_endpoint = None
	api_id_field = "asset_id"
	api_service = "v1"
	api_list_key = 'data.items'
	api_item_key = 'data'
	api_auth = True
	api_single_from_list = False
	api_merge_keys = ()
	api_field_aliases = {'url': 'public_url', 'mime_type': 'content_type'}
	api_child_tables = {}
	api_list_params = {}
	api_cursor_key = None
	api_detail_merge_list = False
	api_write_fields = ()
	api_write_endpoint = None
	api_write_id_field = None
	api_update_method = 'PATCH'
	api_can_create = True
	api_can_delete = True
	api_write_aliases = {}
	api_nested_fields = {}
	api_read_nested = {}
	api_write_child_tables = {}
	api_write_array_fields = ()

	@staticmethod
	def get_list(**kwargs):
		return MarziMedia._api_list(**kwargs)

	@staticmethod
	def get_count(**kwargs):
		return MarziMedia._api_count(**kwargs)

	@staticmethod
	def get_stats(**kwargs):
		return {}
